version = "3.9.9"

runner.dialect = scala3
runner.dialectOverride.allowSignificantIndentation = false
runner.dialectOverride.allowQuietSyntax = true

maxColumn = 80

align {
  preset = most
  arrowEnumeratorGenerator = false
  stripMargin = true
  multiline = true
}
assumeStandardLibraryStripMargin = true

indent {
  main = 4
  significant = 2
  callSite = 2
  defnSite = 2
}

newlines {
  source = fold
  selectChains = unfold

  alwaysBeforeMultilineDef = true
  alwaysBeforeElseAfterCurlyIf = false
  beforeCurlyLambdaParams = never
  afterCurlyLambdaParams = never
  implicitParamListModifierForce = [before]
  avoidForSimpleOverflow = [tooLong, slc]
  avoidInResultType = true
  neverBeforeJsNative = true
  sometimesBeforeColonInMethodReturnType = true

  infix.termSite.maxCountPerExprForSome = 5
}

danglingParentheses {
  defnSite = true
  callSite = false
  ctrlSite = false
}

optIn.breakChainOnFirstMethodDot = false

rewrite {
  trailingCommas.style = multiple
  trailingCommas.allowFolding = true
  
  rules = [RedundantParens, SortImports]
}

